variables:
  major: 0
  minor: 1
  patch: $[counter(format('major {0} minor {1}', variables['major'], variables['minor']), 3)]

name: $[format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch'])]

resources:
  - repo: self

trigger:
  - master

jobs:
  - job: Build
    pool:
      name: Private Linux

    steps:    

      - task: DotNetCoreCLI@2
        displayName: 'Build solution'
        inputs:    
          command: build
          projects: '**/*.csproj'
          arguments: '--configuration Release /p:Version=$(Build.BuildNumber)'
